#ifndef POKEHEARTGOLD_MAP_OBJECT_MOVEMENT_UTILITIES_INTERNAL_H
#define POKEHEARTGOLD_MAP_OBJECT_MOVEMENT_UTILITIES_INTERNAL_H
#include "global.h"

typedef struct LocalMapObject LocalMapObject;
typedef struct MapPosition {
    int x;
    int y;
    int z;
} MapPosition;
extern void sub_0205F41C(LocalMapObject *object);
extern void sub_02063A14(LocalMapObject *object);
extern int MapObject_GetFlagsBitsMask(LocalMapObject *object, u32 mask);
extern void MapObject_ClearFlagsBits(LocalMapObject *object, u32 mask);
extern void MapObject_SetStartMovement(LocalMapObject *object);
extern int sub_02061070(LocalMapObject *object);
extern int sub_02061108(LocalMapObject *object);
extern void sub_0205FEDC(LocalMapObject *object);
extern void sub_02060020(LocalMapObject *object);
extern void sub_0205FF6C(LocalMapObject *object);
extern void sub_02060114(LocalMapObject *object);
extern void sub_0206008C(LocalMapObject *object);
extern void sub_0205F9C0(LocalMapObject *object, VecFx32 *position);
extern int MetatileBehavior_IsSand(u8 behavior);
extern int MetatileBehavior_IsSnow(u8 behavior);
extern int sub_0205B8C4(u8 behavior);
extern int sub_0205BA24(int behavior);
extern int sub_0205BA30(int behavior);
extern int MapObject_CheckFlag28(LocalMapObject *object);
extern void MapObject_SetFlag28(LocalMapObject *object, int value);
extern int MapObject_GetMovement(LocalMapObject *object);
extern void sub_0205F430(LocalMapObject *object);
extern void MapObject_SetFlag26(LocalMapObject *object, int value);
extern int MapObject_GetID(LocalMapObject *object);
extern int MapObject_TestFlagsBits(LocalMapObject *object, u32 mask);
extern int MetatileBehavior_IsVeryTallGrass(u8 behavior);
extern int MetatileBehavior_IsPuddle(u8 behavior);
extern int MetatileBehavior_IsMud(u8 behavior);
extern void ov01_021FF8F0(LocalMapObject *object, int kind);
extern int MapObject_GetXCoord(LocalMapObject *object);
extern int MapObject_GetYCoord(LocalMapObject *object);
extern int MapObject_GetZCoord(LocalMapObject *object);
extern int MapObject_GetPreviousXCoord(LocalMapObject *object);
extern int MapObject_GetPreviousYCoord(LocalMapObject *object);
extern int MapObject_GetPreviousZCoord(LocalMapObject *object);
extern void ov01_021FECA0(LocalMapObject *object, int x, int y, int z);
extern void ov01_021FEE04(LocalMapObject *object, int x, int y, int z);
extern void MapObject_SetPreviousX(LocalMapObject *object, int value);
extern void MapObject_SetPreviousY(LocalMapObject *object, int value);
extern void MapObject_SetPreviousZ(LocalMapObject *object, int value);
extern int MetatileBehavior_IsShallowWater(u8 behavior);
extern int MapObject_CheckFlag26(LocalMapObject *object);
extern void ov01_021FF4FC(LocalMapObject *object, int value);
extern u32 sub_0205F524(LocalMapObject *object);
extern void sub_020603F8(LocalMapObject *object, int a1, u8 value, int a3);
extern void MapObject_CopyPositionVector(LocalMapObject *object, VecFx32 *position);
extern void sub_02060AF4(LocalMapObject *object, VecFx32 *position, int a2, int a3, int a4, int a5);
extern void *MapObject_GetFieldSystem(LocalMapObject *object);
extern int GetMetatileBehavior(void *fieldSystem, int x, int z);
extern int sub_020548EC(void *fieldSystem, int x, int z);
extern int MapObject_GetInitialX(LocalMapObject *object);
extern int MapObject_GetInitialZ(LocalMapObject *object);
extern int MapObject_GetXRange(LocalMapObject *object);
extern int MapObject_GetYRange(LocalMapObject *object);
extern int sub_0205BA54(u8 behavior);
extern int MetatileBehavior_IsSurfableWater(u8 behavior);
extern int sub_0205B78C(u8 behavior);
extern int MapObject_GetSpriteID(LocalMapObject *object);
extern void MapObject_AddCurrentX(LocalMapObject *object, int value);
extern void MapObject_AddCurrentY(LocalMapObject *object, int value);
extern void MapObject_AddCurrentZ(LocalMapObject *object, int value);
extern void MapObject_SetPositionVector(LocalMapObject *object, const VecFx32 *position);
extern int sub_0205F5E8(LocalMapObject *object, int value);
extern void sub_02062400(LocalMapObject *object);
extern int MapObject_CheckMovementPaused(LocalMapObject *object);
extern BOOL sub_0205FD98(LocalMapObject *object);
extern int sub_02063A1C(LocalMapObject *object);
extern int sub_02054940(void *fieldSystem, int y, int x, int z, u8 *behavior);
extern int GetMetatileBehavior_None(void);
extern int MetatileBehavior_IsNone(int behavior);
extern int sub_0205F8D0(LocalMapObject *object);
extern int MapObject_CheckSingleMovement(LocalMapObject *object);
extern u32 MapObject_GetFlags(LocalMapObject *object);
extern void sub_0205F50C(LocalMapObject *object, int behavior);
extern void sub_0205F4FC(LocalMapObject *object, int behavior);
extern void MapObject_SetFlagsBits(LocalMapObject *object, u32 mask);

extern const int _020FD49C[];
extern const int _020FD4AC[];
extern const u32 _020FD4DC[];
typedef BOOL (*BehaviorPredicate)(int value);
extern const BehaviorPredicate _020FD4BC[];
extern const BehaviorPredicate _020FD4CC[];

void sub_0205FD20(LocalMapObject *object);
void sub_0205FD30(LocalMapObject *object);
void sub_0205FE0C(LocalMapObject *object);
void sub_0205FE24(LocalMapObject *object);
void sub_0205FE48(LocalMapObject *object);
void sub_0205FE6C(LocalMapObject *object);
void sub_0205FEA4(LocalMapObject *object);
void sub_020601A4(LocalMapObject *object);
void sub_020603D0(LocalMapObject *object, int a1, int a2, int a3);
void sub_0206039C(LocalMapObject *object, u8 behavior);
void sub_020603DC(LocalMapObject *object, int a1, int unused, int a3);
void sub_02060700(LocalMapObject *object);
void sub_02060704(LocalMapObject *object);
void sub_02060698(LocalMapObject *object, u8 behavior);
void sub_020606CC(LocalMapObject *object, u8 behavior);
void sub_02060708(LocalMapObject *object, u8 unused, u8 behavior);
void sub_0206073C(LocalMapObject *object, u8 behavior);
void sub_02060770(LocalMapObject *object, u8 unused, u8 behavior);
void sub_020607A4(LocalMapObject *object, u8 behavior);
void sub_02060AF0(LocalMapObject *object, int a1, int a2, int a3);
void sub_02060AB8(LocalMapObject *object, int behavior, int a2, int a3);
BOOL sub_02060EA4(LocalMapObject *object, int behavior);
BOOL sub_02060EBC(LocalMapObject *object, int behavior);
BOOL sub_02060ED4(LocalMapObject *object, int behavior);
BOOL sub_02060EEC(LocalMapObject *object, int behavior);
int GetDeltaXByFacingDirection(int direction);
int GetDeltaYByFacingDirection(int direction);
u32 sub_020611F4(u32 direction);
void sub_020611C8(int x, int z, VecFx32 *position);
void sub_020611DC(LocalMapObject *object);
int sub_02061200(int x, int z, int targetX, int targetZ);
void sub_02060F78(LocalMapObject *object);
void sub_02060B90(LocalMapObject *object, int a1, int a2, int a3, int a4);
void sub_02060BB8(LocalMapObject *object, int direction);
BOOL sub_02060D94(LocalMapObject *object, int x, int unused, int z);
BOOL sub_02060E54(LocalMapObject *object, int behavior);
BOOL sub_02060DEC(LocalMapObject *object, int x, int z, int direction);
void sub_02060F24(LocalMapObject *object, int direction);
int sub_02060FA8(LocalMapObject *object, int direction);
u8 sub_02060FE0(LocalMapObject *object, int direction);
void sub_0206101C(LocalMapObject *object, int direction, int distance);
void sub_02061190(int direction, VecFx32 *position, int distance);
BOOL sub_0206121C(void *fieldSystem, MapPosition *position);
BOOL sub_02061248(void *fieldSystem, MapPosition *position, BOOL allowType2);
BOOL sub_02061108(LocalMapObject *object);
extern int sub_0205F73C(LocalMapObject *object);
extern u32 sub_0205F504(LocalMapObject *object);
extern u32 sub_0205F514(LocalMapObject *object);
extern int ov01_021F9318(LocalMapObject *object);
extern void sub_020607D8(LocalMapObject *object, int a1, int a2, int a3);
void sub_02060020(LocalMapObject *object);
extern void sub_0205F51C(LocalMapObject *object, u8 value);
extern void sub_020609D4(LocalMapObject *object, int a1, int a2, int a3);
extern void sub_02060530(LocalMapObject *object, int a1, int a2, int a3);
extern void sub_02060274(LocalMapObject *object, int a1, int a2, int a3);
extern void sub_0206064C(LocalMapObject *object, int a1, int a2, int a3);

void sub_0205FD20(LocalMapObject *object);
void sub_0205FD30(LocalMapObject *object);
BOOL sub_0205FD98(LocalMapObject *object);
void sub_0205FE0C(LocalMapObject *object);
void sub_0205FE24(LocalMapObject *object);
void sub_0205FE48(LocalMapObject *object);
void sub_0205FE6C(LocalMapObject *object);
void sub_0205FEA4(LocalMapObject *object);
void sub_020601A4(LocalMapObject *object);
void sub_020603D0(LocalMapObject *object, int a1, int a2, int a3);
void sub_0206039C(LocalMapObject *object, u8 behavior);
void sub_020603DC(LocalMapObject *object, int a1, int unused, int a3);
void sub_02060700(LocalMapObject *object);
void sub_02060704(LocalMapObject *object);
void sub_02060698(LocalMapObject *object, u8 behavior);
void sub_020606CC(LocalMapObject *object, u8 behavior);
void sub_02060708(LocalMapObject *object, u8 unused, u8 behavior);
void sub_0206073C(LocalMapObject *object, u8 behavior);
void sub_02060770(LocalMapObject *object, u8 unused, u8 behavior);
void sub_020607A4(LocalMapObject *object, u8 behavior);
void sub_02060AF0(LocalMapObject *object, int a1, int a2, int a3);
void sub_02060AB8(LocalMapObject *object, int behavior, int a2, int a3);
BOOL sub_02060EA4(LocalMapObject *object, int behavior);
BOOL sub_02060EBC(LocalMapObject *object, int behavior);
BOOL sub_02060ED4(LocalMapObject *object, int behavior);
BOOL sub_02060EEC(LocalMapObject *object, int behavior);
int GetDeltaXByFacingDirection(int direction);
int GetDeltaYByFacingDirection(int direction);
u32 sub_020611F4(u32 direction);
void sub_020611C8(int x, int z, VecFx32 *position);
void sub_020611DC(LocalMapObject *object);
int sub_02061200(int x, int z, int targetX, int targetZ);
void sub_02060F78(LocalMapObject *object);
void sub_02060B90(LocalMapObject *object, int a1, int a2, int a3, int a4);
void sub_02060BB8(LocalMapObject *object, int direction);
BOOL sub_02060E54(LocalMapObject *object, int behavior);
void sub_02060F24(LocalMapObject *object, int direction);
int sub_02060FA8(LocalMapObject *object, int direction);
u8 sub_02060FE0(LocalMapObject *object, int direction);
void sub_0206101C(LocalMapObject *object, int direction, int distance);
void sub_02061190(int direction, VecFx32 *position, int distance);
BOOL sub_0206121C(void *fieldSystem, MapPosition *position);
BOOL sub_02061248(void *fieldSystem, MapPosition *position, BOOL allowType2);
BOOL sub_02061108(LocalMapObject *object);
void sub_02060020(LocalMapObject *object);

#endif
