#include "global.h"

typedef struct OverlayManager OverlayManager;
extern void *OverlayManager_GetData(OverlayManager *);
extern void OverlayManager_FreeData(OverlayManager *);
extern void *OverlayManager_GetArgs(OverlayManager *);
extern void *OverlayManager_CreateAndGetData(OverlayManager *, u32, u32);
extern void Heap_Create(u32, u32, u32);
extern void Heap_Destroy(u32);
extern void MI_CpuFill8(void *, u8, u32);
extern void *memset(void *, int, u32);
extern int MailMsg_IsInit(void *);
extern void PaletteData_BlendPalette(void *, u32, u32, s32, u32, u16);
extern int System_GetTouchHeld(void);
extern int System_GetTouchNew(void);
extern void PlaySE(u16);
extern void TextFlags_SetCanABSpeedUpPrint(int);
extern int Options_GetTextFrameDelay(void *);
extern int Options_GetFrame(void *);
extern int MenuInputStateMgr_GetState(void *);
extern void MenuInputStateMgr_SetState(void *, int);
extern int YesNoPrompt_HandleInput(void *);
extern void YesNoPrompt_InitFromTemplateWithPalette(void *, void *, void *);
extern int YesNoPrompt_IsInTouchMode(void *);
extern void YesNoPrompt_Reset(void *);
extern void YesNoPrompt_Destroy(void *);
extern void ClearWindowTilemapAndCopyToVram(void *);
extern void RemoveWindow(void *);
extern void FreeBgTilemapBuffer(void *, int);
extern void Heap_Free(void *);
extern void PaletteData_FreeBuffers(void *, int);
extern void PaletteData_Free(void *);
extern void G2x_SetBlendAlpha_(u32, int, int, int, int);
extern void Sprite_DeleteAndFreeResources(void *);
extern void SpriteSystem_FreeResourcesAndManager(void *, void *);
extern void SpriteSystem_Free(void *);
extern void GF_DestroyVramTransferManager(void);
extern void DestroyMsgData(void *);
extern void GfGfx_SetBanks(void *);
extern void DrawFrameAndWindow2(void *, int, int, int);
extern void FillWindowPixelBuffer(void *, int);
extern void *String_New(u32, u32);
extern void String_Delete(void *);
extern void ReadMsgDataIntoString(void *, int, void *);
extern int AddTextPrinterParameterizedWithColor(void *, int, void *, int, int, int, u32, void *);
extern void ClearFrameAndWindow2(void *, int);
extern int TextPrinterCheckActive(u8);
extern int TouchscreenHitbox_FindRectAtTouchNew(const void *);
extern int DoesPixelAtScreenXYMatchPtrVal(void *, int, u16, u16, const u16 *);
extern void AddWindowParameterized(void *, void *, int, int, int, int, int, int, int);
extern void CopyWindowToVram(void *);
extern void *YesNoPrompt_Create(u32);
extern void *MailMsg_GetExpandedString(void *, u32);
extern void *NewMsgDataFromNarc(int, int, int, u32);
extern void String_SetEmpty(void *);
extern int FontID_String_GetWidth(int, void *, int);
extern void PaletteData_PushTransparentBuffers(void *);
extern void SpriteSystem_TransferOam(void *);
extern void NNS_GfdDoVramTransfer(void);
extern void DoScheduledBgGpuUpdates(void *);
extern void SysTask_Destroy(void *);
extern void Main_SetVBlankIntrCB(void *, void *);
extern void HBlankInterruptDisable(void);
extern void GfGfx_DisableEngineAPlanes(void);
extern void GfGfx_DisableEngineBPlanes(void);
extern void sub_0200FBF4(int, int);
extern void ResetVisibleHardwareWindows(int);
extern void GfGfx_EngineATogglePlanes(int, int);
extern void SetMasterBrightnessNeutral(int);
extern void PaletteData_BeginPaletteFade(void *, int, u16, int, int, int, int);
extern int PaletteData_GetSelectedBuffersBitmask(void *);
extern void SpriteSystem_DrawSprites(void *);
extern void *BgConfig_Alloc(u32);
extern void SetBothScreensModesAndDisable(void *);
extern void InitBgFromTemplate(void *, int, const void *, int);
extern void BgClearTilemapBufferAndCommit(void *, int);
extern void BG_ClearCharDataRange(int, int, int, u32);

extern u8 gSystem[];

int ov56_021E6228(void *);
int ov56_021E5C9C(OverlayManager *);
int ov56_021E5C20(OverlayManager *);
int ov56_021E5CB4(OverlayManager *);
void ov56_021E5D08(void *);
int ov56_021E5CE0(void *);
int ov56_021E5D34(void *);
int ov56_021E5D40(void);
int ov56_021E5D44(void *);
int ov56_021E5DA4(void *);
int ov56_021E5DDC(void *);
int ov56_021E5EFC(void *);
int ov56_021E5FB4(void *);
int ov56_021E5FDC(void *);
int ov56_021E60F4(void *);
void ov56_021E609C(void *);
int ov56_021E614C(void *);
void ov56_021E660C(void *);
void ov56_021E692C(void *);
void ov56_021E6A7C(void *);
void ov56_021E6D90(void *);
void ov56_021E63C0(void *);
void ov56_021E63FC(void *, void *);
void ov56_021E64F4(void);
int ov56_021E647C(void *);
int ov56_021E64C8(void *);
void ov56_021E6514(void *);
void ov56_021E6650(void *);
void ov56_021E696C(void *);
void ov56_021E6AA4(void *);
void ov56_021E6BB4(void *);
