#ifndef POKEHEARTGOLD_PLAYER_AVATAR_MOVEMENT_CONTROL_INTERNAL_H
#define POKEHEARTGOLD_PLAYER_AVATAR_MOVEMENT_CONTROL_INTERNAL_H
#include "global.h"

typedef struct PlayerAvatar PlayerAvatar;
typedef struct MapObject MapObject;

typedef struct MovementLookupEntry {
    BOOL (*predicate)(u8 value);
    int result;
} MovementLookupEntry;

extern int sub_0205CBEC(PlayerAvatar *, int, int, int);
extern MapObject *PlayerAvatar_GetMapObject(PlayerAvatar *);
extern BOOL MapObject_AreBitsSetForMovementScriptInit(MapObject *);
extern void sub_02060FA8(MapObject *, int);
extern void PlayerAvatar_SetUnk8(PlayerAvatar *, int);
extern void MapObject_SetHeldMovement(MapObject *, int);
extern void PlayerAvatar_SetMoveState(PlayerAvatar *, int);
extern void PlayerAvatar_SetPlayerMoveState(PlayerAvatar *, int);
extern void PlayerAvatar_ClearUnk24ClearFlag2(PlayerAvatar *);
extern int PlayerAvatar_GetUnk8(PlayerAvatar *);
extern int PlayerAvatar_GetNextFacingDirection(PlayerAvatar *);
extern int PlayerAvatar_GetUnk28(PlayerAvatar *);
extern int PlayerAvatar_GetUnk2C(PlayerAvatar *);
extern void PlayerAvatar_SetUnk28Unk2C(PlayerAvatar *, int, int);
extern void PlayerAvatar_ClearFlag6(PlayerAvatar *);
extern BOOL PlayerAvatar_CheckFlag6(PlayerAvatar *);
extern int PlayerAvatar_GetMoveState(PlayerAvatar *);
extern int PlayerAvatar_GetPlayerMoveState(PlayerAvatar *);
extern void PlayerAvatar_SetFlag1(PlayerAvatar *, BOOL);
extern int PlayerAvatar_GetUnk24(PlayerAvatar *);
extern void PlayerAvatar_SetUnk24(PlayerAvatar *, int);
extern int sub_0206234C(int, int);
extern int PlayerAvatar_Unk24AddWithCeiling(PlayerAvatar *, int, int);
extern BOOL PlayerAvatar_CheckFlag2(PlayerAvatar *);
extern void PlayerAvatar_SetFlag2(PlayerAvatar *, BOOL);
extern int PlayerAvatar_GetFacingDirection(PlayerAvatar *);
extern int PlayerAvatar_GetXCoord(PlayerAvatar *);
extern int PlayerAvatar_GetZCoord(PlayerAvatar *);
extern int GetDeltaXByFacingDirection(int);
extern int GetDeltaYByFacingDirection(int);
extern void GF_AssertFail(void);
extern void MapObject_SetFacingDirection(MapObject *, int);
extern void sub_0205F328(MapObject *, int);
extern void sub_02060F78(MapObject *);
extern void MapObject_ClearHeldMovement(MapObject *);
extern BOOL PlayerAvatar_CheckForcedMovement(PlayerAvatar *);
extern void MapObject_ClearFlagsBits(MapObject *, u32);
extern BOOL PlayerAvatar_CheckFlag7(PlayerAvatar *);
extern void PlayerAvatar_SetForcedMovement(PlayerAvatar *, BOOL);
extern void PlayerAvatar_SetFlag7(PlayerAvatar *, BOOL);
extern void PlayerAvatar_SetFlag5(PlayerAvatar *, BOOL);
extern int MapObject_GetFacingDirection(MapObject *);
extern void MapObject_SetNextFacingDirection(MapObject *, int);
extern void PlayerAvatar_ResetUnkC(PlayerAvatar *);
extern void PlayerAvatar_ToggleUnkC(PlayerAvatar *);
extern int MapObject_GetMovementCommand(MapObject *);
extern BOOL FollowMon_IsActive(void *fieldSystem);
extern int MapObject_GetPreviousXCoord(MapObject *);
extern int MapObject_GetPreviousZCoord(MapObject *);
extern void ov01_02205990(int movement, int x, int z, void *followMon);
extern void MapObject_CopyPositionVector(MapObject *, VecFx32 *);
extern void sub_02061190(void *arg, VecFx32 *position, int distance);
extern BOOL sub_0206121C(void *fieldSystem, VecFx32 *position);
extern int sub_0205F504(MapObject *);
extern BOOL PlayerAvatar_CheckFlag1(PlayerAvatar *);
extern const MovementLookupEntry _020FCB88[];
extern void *MapObject_GetFieldSystem(MapObject *);
extern void *Save_GameStats_Get(void *saveData);
extern void GameStats_Inc(void *stats, int stat);
extern int PlayerAvatar_GetState(PlayerAvatar *);
extern BOOL PlayerAvatar_CheckBikeStateLocked(PlayerAvatar *);
extern BOOL sub_02060EEC(MapObject *, int);
extern int MapObject_GetXCoord(MapObject *);
extern int MapObject_GetZCoord(MapObject *);
extern u32 GetMetatileBehavior(void *fieldSystem, int x, int z);
extern BOOL sub_02060E54(MapObject *, u32 behavior);
typedef BOOL (*MovementPredicate)(PlayerAvatar *, int);
extern MovementPredicate _020FCB7C[];

int sub_0205D44C(int a0, int a1, int a2);
int sub_0205CBE4(PlayerAvatar *avatar, int a1, int a2, int a3);
int sub_0205DD94(PlayerAvatar *avatar, int unused, int keys);
int sub_0205DDD4(PlayerAvatar *avatar, int unused, int keys);
BOOL sub_0205DFC8(PlayerAvatar *avatar);
void sub_0205DFEC(PlayerAvatar *avatar, int value);
BOOL sub_0205DE88(int a0, int flags);
void sub_0205DA1C(PlayerAvatar *avatar, MapObject *mapObject, int movement);
void sub_0205CF44(PlayerAvatar *avatar);
int sub_0205DD9C(int keys);
int sub_0205DDB8(int keys);
BOOL sub_0205DE64(int value);
BOOL sub_0205DE98(PlayerAvatar *avatar);
void sub_0205CC74(PlayerAvatar *avatar);
BOOL sub_0205D2A0(PlayerAvatar *avatar, int direction);
int sub_0205D658(PlayerAvatar *avatar, int value);
BOOL sub_0205D684(PlayerAvatar *avatar);
BOOL sub_0205D6B4(PlayerAvatar *avatar);
int sub_0205D450(PlayerAvatar *avatar, int direction);
void sub_0205DFFC(PlayerAvatar *avatar, int direction, int *x, int *z);
int sub_0205D428(int value);
int sub_0205D778(int value);
void sub_0205CFBC(PlayerAvatar *avatar, int direction);
void sub_0205D1FC(PlayerAvatar *avatar);
void sub_0205E048(PlayerAvatar *avatar);
BOOL sub_0205E078(PlayerAvatar *avatar, int direction, int value);
BOOL sub_0205DCA0(void *unused, MapObject *mapObject, int direction);
BOOL sub_0205D07C(PlayerAvatar *avatar, int index, int value);
int sub_0205D09C(PlayerAvatar *avatar);
int sub_0205D40C(PlayerAvatar *avatar, int direction);
void sub_0205D494(PlayerAvatar *avatar, MapObject *mapObject);
void sub_0205D818(PlayerAvatar *avatar, MapObject *mapObject);
void sub_0205D948(PlayerAvatar *avatar, MapObject *mapObject, int direction);
void sub_0205D610(PlayerAvatar *avatar, MapObject *mapObject, int direction);
BOOL sub_0205DE38(PlayerAvatar *avatar);
int sub_0205D01C(PlayerAvatar *avatar, int value);
BOOL sub_0205D004(PlayerAvatar *avatar, int value);
void sub_0205CC4C(PlayerAvatar *avatar, int unused1, int unused2, int keys);
int sub_0205DEC0(PlayerAvatar *avatar, int direction);
BOOL sub_0205CF60(PlayerAvatar *avatar);
void sub_0205D2D0(PlayerAvatar *avatar, int direction);
int sub_0205D240(PlayerAvatar *avatar, void *arg);
int sub_0205D7AC(PlayerAvatar *avatar, int direction);
int sub_0205D75C(PlayerAvatar *avatar, int direction);
void PlayerAvatar_GetCoordsInFront(PlayerAvatar *avatar, int *x, int *z);
void sub_0205DFD4(PlayerAvatar *avatar, int movement);

int sub_0205D44C(int a0, int a1, int a2);
int sub_0205CBE4(PlayerAvatar *avatar, int a1, int a2, int a3);
int sub_0205DD94(PlayerAvatar *avatar, int unused, int keys);
BOOL sub_0205DFC8(PlayerAvatar *avatar);
void sub_0205DFEC(PlayerAvatar *avatar, int value);
void sub_0205DFD4(PlayerAvatar *avatar, int movement);
void PlayerAvatar_GetCoordsInFront(PlayerAvatar *avatar, int *x, int *z);
BOOL sub_0205DE88(int a0, int flags);
void sub_0205DA1C(PlayerAvatar *avatar, MapObject *mapObject, int movement);
void sub_0205CF44(PlayerAvatar *avatar);
void sub_0205CFBC(PlayerAvatar *avatar, int direction);
BOOL sub_0205CF60(PlayerAvatar *avatar);
void sub_0205D1FC(PlayerAvatar *avatar);
void sub_0205E048(PlayerAvatar *avatar);
BOOL sub_0205E078(PlayerAvatar *avatar, int direction, int value);
BOOL sub_0205DCA0(void *unused, MapObject *mapObject, int direction);
void sub_0205CC74(PlayerAvatar *avatar);
void sub_0205CC4C(PlayerAvatar *avatar, int unused1, int unused2, int keys);
BOOL sub_0205D2A0(PlayerAvatar *avatar, int direction);
void sub_0205D2D0(PlayerAvatar *avatar, int direction);
int sub_0205D240(PlayerAvatar *avatar, void *arg);
BOOL sub_0205D07C(PlayerAvatar *avatar, int index, int value);
int sub_0205D01C(PlayerAvatar *avatar, int value);
BOOL sub_0205D004(PlayerAvatar *avatar, int value);
int sub_0205D09C(PlayerAvatar *avatar);
int sub_0205D658(PlayerAvatar *avatar, int value);
BOOL sub_0205D684(PlayerAvatar *avatar);
BOOL sub_0205D6B4(PlayerAvatar *avatar);
int sub_0205D7AC(PlayerAvatar *avatar, int direction);
int sub_0205D75C(PlayerAvatar *avatar, int direction);
int sub_0205D450(PlayerAvatar *avatar, int direction);
int sub_0205D428(int value);
int sub_0205D40C(PlayerAvatar *avatar, int direction);
void sub_0205D494(PlayerAvatar *avatar, MapObject *mapObject);
void sub_0205D818(PlayerAvatar *avatar, MapObject *mapObject);
void sub_0205D948(PlayerAvatar *avatar, MapObject *mapObject, int direction);
void sub_0205D610(PlayerAvatar *avatar, MapObject *mapObject, int direction);
BOOL sub_0205DE38(PlayerAvatar *avatar);
int sub_0205D778(int value);
void sub_0205DFFC(PlayerAvatar *avatar, int direction, int *x, int *z);
int sub_0205DD9C(int keys);
int sub_0205DDB8(int keys);
int sub_0205DDD4(PlayerAvatar *avatar, int unused, int keys);
BOOL sub_0205DE64(int value);
BOOL sub_0205DE98(PlayerAvatar *avatar);
int sub_0205DEC0(PlayerAvatar *avatar, int direction);

#endif
