#ifndef POKEHEARTGOLD_OVERLAY70_MENU_INPUT_R13_PRIVATE_H
#define POKEHEARTGOLD_OVERLAY70_MENU_INPUT_R13_PRIVATE_H

#include "global.h"

int ov70_02239834(void *work);

#endif // POKEHEARTGOLD_OVERLAY70_MENU_INPUT_R13_PRIVATE_H
